version: "3.9"

services:
  express-api:
    build: ./services/express-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_USER_PASSWORD}@db/${DB_NAME}
    env_file:
      - ./.env

  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - "db_data:/var/lib/mysql"
    env_file:
      - ./.env

  react-frontend:
    build: ./services/react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - express-api
    volumes:
      - "/app/node_modules"

volumes:
  db_data:
